config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  root 'users#index'

  resources :users, except: [:destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :questions, except: [:show, :new, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true

  validates :text, :user, presence: true
  validates :text, length: { maximum: 255 }
end

app/models/user.rb
require 'openssl'

class User < ApplicationRecord
  # Параметры работы модуля шифрования паролей
  ITERATIONS = 20000
  DIGEST = OpenSSL::Digest::SHA256.new

  has_many :questions

  attr_accessor :password

  validates :email, presence: true, uniqueness: true, 'valid_email_2/email': true
  validates :username, presence: true, length: {minimum: 3, maximum: 40}, format: {
    with: /\A\w+\z/,
    message: "only allows letters, numbers or _"
  }
  validates :password, presence: true, on: :create, confirmation: true
  validates :bgcolor, format: { with: /\A#[\h]{6}\z/ }, allow_nil: true, on: :update

  before_validation :downcase!
  before_save :encrypt_password

  def self.hash_to_string(password_hash)
    password_hash.unpack('H*')[0]
  end

  def self.authenticate(email, password)
    user = find_by(email: email.downcase) # Ищем email в #users

    # Сравниваем хэш паролей, исходный пароль не сохраняется.
    return nil unless user.present?

    hashed_password = User.hash_to_string(
      OpenSSL::PKCS5.pbkdf2_hmac(
        password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST
      )
    )

    return user if user.password_hash == hashed_password
    nil
  end

  def encrypt_password
    if password.present?
      # Создаем соль - рандомная строка, усложняющая энкрипт паролей
      self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))

      # Создаем хэш пароля - длинная уникальная строка, из которой невозмодно восстановить исходный пароль
      self.password_hash = User.hash_to_string(OpenSSL::PKCS5.pbkdf2_hmac(
        password, password_salt, ITERATIONS, DIGEST.length, DIGEST)
      )
    end
  end

  private

  def downcase!
    self.username&.downcase!
    self.email&.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def reject_user
    redirect_to root_path, alert: 'Доступ запрещен'
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_question, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, except: [:create]

  def edit
  end

  def create
    @question = Question.new(question_params)
    @question.author = current_user

    if check_captcha(@question) && @question.save
      redirect_to user_path(@question.user), notice: "Вопрос успешно создан"
    else
      render :edit
    end
  end

  def update
    if @question.update(question_params)
      redirect_to user_path(@question.user), notice: "Вопрос обновлен"
    else
      render :edit
    end
  end

  def destroy
    user = @question.user
    @question.destroy
    redirect_to user_path(user), notice: 'Вопрос удален'
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def authorize_user
    reject_user unless @question.user == current_user
  end

  def question_params
    if current_user.present? &&
      params[:question][:user_id].to_i == current_user.id
      params.require(:question).permit(:user_id, :text, :answer)
    else
      params.require(:question).permit(:user_id, :text)
    end
  end

  def check_captcha(model)
    if current_user.present?
      true
    else
      verify_recaptcha(model: model)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])

    if user.present?
      session[:user_id] = user.id
      redirect_to root_path, notice: "Вы успешно вошли"
    else
      flash.now.alert = 'Неправильный email или пароль'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Вы ушли с сайта. Ждем вас снова!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :load_user, except: [:index, :create, :new]
  before_action :authorize_user, except: [:index, :new, :create, :show]

  def index
    @users = User.all
  end

  def new
    redirect_to root_url, alert: 'Вы уже вошли' if current_user.present?
    @user = User.new
  end

  def create
    redirect_to root_url, alert: 'Вы уже вошли' if current_user.present?
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Пользователь успешно зарегистрирован"
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "Профиль успешно обновлен"
    else
      render 'edit'
    end
  end

  def edit
  end

  def show
    @questions = @user.questions.order(created_at: :desc)
    @new_question = @user.questions.build

    @questions_count = @questions.count
    @answers_count = @questions.where.not(answer: nil).count
    @unanswered_count = @questions_count - @answers_count
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Ваш профиль успешно удален"
  end

  private

  def authorize_user
    reject_user unless @user == current_user
  end
  
  def load_user
    @user ||= User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 :name, :username, :avatar_url, :bgcolor)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def question_forms
   %w[вопрос вопроса вопросов]
  end

  def user_avatar(user)
    if user.avatar_url.present?
      user.avatar_url
    else
      asset_path 'avatar.jpg'
    end
  end

  def pluralize(number, one, few, many)
    return many if number % 100 >= 11 && number % 100 <= 14

    case number % 10
    when 1 then one
    when 2, 3, 4 then few
    else many
    end
  end

  def num_pluralize(number, one, few, many)
    "#{number} #{pluralize(number, one, few, many)}"
  end

  def question_pluralize(count)
    num_pluralize(count, *question_forms)
  end

  def fa_icon(icon_class)
    content_tag 'span', '', class: "fas fa-#{icon_class}"
  end

  def author(question)
    if question.author.present?
      link_to_unless_current(question.author.username, user_path(question.author))
    else
      'anonymous'
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset='UTF-8'
    title Хорошие вопросы
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .header
      .container
        .header-logo
          h1.header-title = link_to "Хорошие вопросы", root_path
        .header-nav
          - if current_user
            = link_to "@#{current_user.username}", user_path(current_user)
            | |
            = link_to 'Выйти', session_path, data: {method: :delete}
          - else
            = link_to 'Зарегистрироваться', new_user_path,
            class: 'button button-light button-small'
            = link_to 'Войти', new_session_path,
            class: 'button button-light button-small'
    .content
      .container
        - if flash.any?
          .content-wrapper.buffer-both
            - flash.each do |name, message|
              = content_tag :div, message, class: "flash-#{name}"
        = yield

app/views/questions/_form.html.slim
.form
  = form_for @question do |f|
    - if @question.errors.any?
      .form-errors
        ul
          - @question.errors.full_messages.each do |message|
            li.form-error-message = message

    = f.hidden_field :user_id
    .form-field
      = f.label :text, 'Вопрос', class: 'form-label'
      = f.text_area :text, class: 'form-text-area'
    - if current_user.present? && current_user == @question.user
      .form-field
        = f.label :answer, 'Ответ', class: 'form-label'
        = f.text_area :answer, class: 'form-text-area'

    = recaptcha_tags unless current_user.present?
    .form-action.buffer-both
      = f.submit 'Сохранить', class: 'button button-dark button-small'
      ' или
      =  link_to 'Вернуться', user_path(@question.user)

app/views/questions/_question.html.slim
- question ||= nil
- action_icon = question.answer.blank? ? 'reply' : 'pencil-alt'

.question
  .question-content
    .question-text.text-lead
      = question.text
    - if question.answer.present?
      .question-answer.text-lead
        = question.answer if question.answer.present?
    .question-date
      = l(question.created_at, format: :short)
      ',
      ' author: @#{author(question)}
  - if question.user == current_user
    .question-actions
      = link_to fa_icon(action_icon), edit_question_path(question)
      = link_to fa_icon('trash-alt'), question_path(question), method: :delete, data: {confirm: 'Удалить вопрос?'}

app/views/questions/edit.html.slim
.container.content-wrapper.buffer-both
  h1.title-medium  Вопрос
  .column-1-2
    = render 'form'

app/views/users/edit.html.slim
.container.content-wrapper.buffer-both
  h1.title-medium Изменить профиль
  .column-1-2
    = form_for(@user) do |f|
      - if @user.errors.any?
        .form-errors
          ul
            - for message in @user.errors.full_messages
              li.form-error-message = message
      .form-field
        = f.label :username, class: 'form-label'
        = f.text_field :username, class: 'form-text-field'
      .form-field
        = f.label 'Ваше имя', class: 'form-label'
        = f.text_field :name, class: 'form-text-field'
      .form-field
        = f.label 'URL вашей аватарки', class: 'form-label'
        = f.text_field :avatar_url, class: 'form-text-field'
      .form-field
        = f.label 'Цвет фона профиля', class: 'form-label'
        = f.color_field :bgcolor
      .buffer-top-large.buffer-bottom
        | Если не хотите менять пароль — оставьте эти поля пустыми!
      .form-field
        = f.label :password, class: 'form-label'
        = f.text_field :password, class: 'form-text-field'
      .form-field
        = f.label :password_confirmation, class: 'form-label'
        = f.text_field :password_confirmation, class: 'form-text-field'
      .form-action.buffer-top
        = f.submit 'Сохранить', class: 'button button-dark button-small'
        = link_to 'Удалить пользователя', user_path, method: :delete,
                data: {confirm: 'Если Вы уверены, то нажмите да'},
                class: 'button button-red button-small'

app/views/users/index.html.slim
.content-wrapper.buffer-both.text-center
  .buffer-both
    h1.title-medium Наши пользователи
  - @users.each do |user|
    .users-list-item
      .user-image-div.user-image-div-small
        = link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user)

app/views/users/new.html.slim
.container.content-wrapper.buffer-both
  h1.title-medium Присоединяйся к нам
  .column-1-2
    = form_for @user do |f|
      - if @user.errors.any?
        .form-errors
          ul
            - for message in @user.errors.full_messages
              li.form-error-message = message
      .form-field
        = f.label :email, 'Логин (email)', class: 'form-label'
        = f.email_field :email, class: 'form-text-field'
      .form-field
        = f.label :username, 'Никнейм', class: 'form-label'
        = f.text_field :username, class: 'form-text-field'
      .form-field
        = f.label :name, 'Имя', class: 'form-label'
        = f.text_field :name, class: 'form-text-field'
      .form-field
        = f.label :password, 'Пароль', class: 'form-label'
        = f.password_field :password, class: 'form-text-field'
      .form-field
        = f.label :password_confirmation, 'Пароль ещё раз', class: 'form-label'
        = f.password_field :password_confirmation, class: 'form-text-field'
      .form-action
        = f.submit 'Зарегистрироваться', class: 'button button-small button-dark'

app/views/users/show.html.slim
.user-header.text-center style="background: #{@user.bgcolor}"
  h1.text-medium = @user.name
  .buffer-both
    = link_to 'Редактировать профиль', edit_user_path(@user) if current_user == @user
  .user-image-div = image_tag user_avatar(@user), class: 'user-image', alt: '[avatar]'
  h2.title-small.buffer-both  @#{@user.username}
  .user-header
    .user-details
      .user-ask-button.container.text-center
        = link_to "Спроси меня", '', class: 'button button-light', id: 'ask-button'
      .user-statistics.container.text-center
        .content
          .column-1-3
            p 
              strong Всего:
            p #{question_pluralize(@questions_count)}
          .column-1-3
            p
              strong Отвеченных:
            p #{question_pluralize(@answers_count)}
          .column-1-3
            p
              strong Не отвеченных:
            p #{question_pluralize(@unanswered_count)}
.user-question-form-div.column-1-4.column-1-4-right id='ask-form'
  .user-question-form.buffer-both
    .form
      = form_for @new_question do |f|
        = f.hidden_field :user_id
        .form-field
          = f.label "Ваш вопрос для @#{@user.username}", class: 'form-label'
          = f.text_area :text, class: 'form-textarea'
        = recaptcha_tags size: 'compact' unless current_user.present?
        .form-action
          = submit_tag 'Задать вопрос', class: 'button button-small button-dark'
          
.column-3-4
  .user-questions.buffer-both
    - @questions.each do |question|
      = render partial: 'questions/question', object: question